{ pkgs }: {
    deps = [
      pkgs.elastix
      pkgs.haskellPackages.nonemptymap
      pkgs.emacs27Packages.css-autoprefixer
      pkgs.perlPackages.GitAutofixup
      pkgs.perl534Packages.GitAutofixup
      pkgs.perl532Packages.GitAutofixup
      pkgs.haskellPackages.ghc-pkg-autofix
      pkgs.rPackages.gamlss_data
      pkgs.emacs27Packages.auto-complete-exuberant-ctags
      pkgs.emacs27Packages.auto-complete-sage
      pkgs.emacs27Packages.auto-complete-rst
      pkgs.emacs27Packages.auto-complete-distel
      pkgs.emacs27Packages.auto-complete-c-headers
      pkgs.emacs27Packages.auto-complete-chunk
      pkgs.emacs27Packages.auto-complete-auctex
      pkgs.emacs27Packages.auto-complete-clang-async
      pkgs.emacs27Packages.auto-complete-pcmp
      pkgs.emacs27Packages.auto-complete-nxml
      pkgs.emacs27Packages.auto-complete
      pkgs.rPackages.dotwhisker
      pkgs.nodePackages_latest.textlint-rule-period-in-list-item
      pkgs.nodePackages.textlint-rule-period-in-list-item
      pkgs.rPackages.googlePublicData
      pkgs.rPackages.economiccomplexity
      pkgs.haskellPackages.concurrent-split
      pkgs.rPackages.episplineDensity
      pkgs.haskellPackages.gogol-replicapool-updater
      pkgs.haskellPackages.greplicate
      pkgs.rPackages.epanet2toolkit
      pkgs.rPackages.ANOVAreplication
      pkgs.vimPlugins.vim-ReplaceWithRegister
      pkgs.haskellPackages.regex-applicative
      pkgs.vimPlugins.vim-ReplaceWithSameIndentRegister
      pkgs.emacs27Packages.evil-replace-with-char
      pkgs.rPackages.HighlyReplicatedRNASeq
      pkgs.emacs27Packages.evil-replace-with-register
      pkgs.rPackages.mcreplicate
      pkgs.haskellPackages.regex-applicative-text
      pkgs.haskellPackages.postgresql-replicant
      pkgs.rPackages.replicatedpp2w
      pkgs.rPackages.Replication
      pkgs.rPackages.Replicate
      pkgs.rPackages.replicationInterval
      pkgs.haskellPackages.repl-toolkit
      pkgs.vimPlugins.ReplaceWithRegister
      pkgs.haskellPackages.ReplicateEffects
      pkgs.rPackages.ipr
      pkgs.k2pdfopt
      pkgs.python38Packages.qiskit-ibmq-provider
      pkgs.haskellPackages.uuid-le
      pkgs.rustc
      pkgs.quicklispPackagesSBCL.fiveam
      pkgs.rPackages.LDRTools
      pkgs.perl534Packages.CommonSense
      pkgs.emacs27Packages.evil-visual-mark-mode
      pkgs.postgresql13Packages.tds_fdw
      pkgs.rPackages.Rvmmin
      pkgs.rPackages.d3Network
      pkgs.haskellPackages.gen-passwd
      pkgs.haskellPackages.network-data
      pkgs.rPackages.bfw
      pkgs.python39Packages.pysma
      pkgs.sutils
      pkgs.vimPlugins.vim-dadbod-completion
      pkgs.emacs27Packages.json-navigator
      pkgs.rPackages.annotatr
      pkgs.libint
      pkgs.haskellPackages.stripe-concepts
      pkgs.haskellPackages.stripe-hs
      pkgs.haskellPackages.stripe-core
      pkgs.emacs27Packages.stripes
      pkgs.haskellPackages.stripe-signature
      pkgs.haskellPackages.stripe-http-client
      pkgs.haskellPackages.stripeapi
      pkgs.stripe-cli
      pkgs.python38Packages.stripe
      pkgs.python39Packages.stripe
      pkgs.haskellPackages.stripe
      pkgs.python39Packages.nix-prefetch-github
      pkgs.nix-prefetch-scripts
      pkgs.nix-doc
      pkgs.nixfmt
      pkgs.haskellPackages.nix-linter
      pkgs.nix-build-uncached
      pkgs.nix-binary-cache
      pkgs.nix-delegate
      pkgs.nix-prefetch-bzr
      pkgs.nix
      pkgs.nixFlakes
      pkgs.nixStatic
      pkgs.nixUnstable
      pkgs.nixStable
      pkgs.perl532Packages.TextWrapI18N
      pkgs.rPackages.adnuts
      pkgs.cowsay
    ];
}