{pkgs}: {
  deps = [
    pkgs.haskellPackages.openapi3-code-generator
    pkgs.openapi-generator-cli
    pkgs.sbclPackages.openapi-generator
    pkgs.openapi-tui
    pkgs.python312Packages.openapi-schema-validator
    pkgs.haskellPackages.openapi-typed
    pkgs.sbclPackages.openapi-parser-tests
    pkgs.python312Packages.openapi-core
    pkgs.python311Packages.openaiauth
    pkgs.openai-triton-llvm
    pkgs.haskellPackages.openai-servant
    pkgs.haskellPackages.openai-hs
    pkgs.python312Packages.openai
    pkgs.openai
    pkgs.github-runner
    pkgs.emacsPackages.github-clone
    pkgs.haskellPackages.github
    pkgs.haskellPackages.stripeapi
    pkgs.haskellPackages.stripe-hs
    pkgs.haskellPackages.stripe-concepts
    pkgs.haskellPackages.stripe-core
    pkgs.stripe-cli
    pkgs.emacsPackages.stripes
    pkgs.python311Packages.stripe
    pkgs.haskellPackages.stripe
    pkgs.python312Packages.stripe
    pkgs.sbclPackages.stripe
    pkgs.sbclPackages.latter-day-paypal
    pkgs.sbclPackages.cl-paypal
    pkgs.python311Packages.paypalrestsdk
    pkgs.haskellPackages.paypal-adaptive-hoops
    pkgs.python311Packages.paypal-checkout-serversdk
    pkgs.python311Packages.paypalhttp
    pkgs.python312Packages.paypalrestsdk
    pkgs.python312Packages.paypal-checkout-serversdk
    pkgs.luastatus
    pkgs.swayidle
    pkgs.python311Packages.anthropic
    pkgs.python312Packages.anthropic
    pkgs.chatgpt-retrieval-plugin
  ];
}
